### PR TITLE
Create a basic range detector script for RGB and HSV filters

### PR DESCRIPTION
**Pull request by marjinal1st**
Cleaned up one of my (terrible) scripts for detecting RGB-HSV ranges and put it in the package.

I know that's not directly related to your book, but I think it's pretty useful for Python-OpenCV learners to quickly lookup RGB-HSV range values.

Script opens up 3 windows: Image source (webcam or file), thresholded image and trackbars.

Hope you merge it :smile:

### CODE REVIEW

**Comment by jrosebr1** [comment]
Very cool! I just downloaded it and gave it a try. We can definitely merge it in, just a few suggestions first.

1. I would reorganize the trackbars a bit so they are in "H_min", "H_max", "S_min", "S_max", etc. order rather than "H_min", "S_min", "V_min", etc. order. It was a little confusing when I first launched the script. I hope that makes sense.
2. Can you put an example usage of executing the script at the top of the file? This is something I do for many source code downloads on PyImageSearch, for example:

<pre># USAGE
# python load_display_save.py --image ../images/trex.png</pre>

I find having a few example usages at the top of script files really helps people when they try to execute it. It's a bit nit-picky, but a convention I would like to maintain.

**Comment by marjinal1st** [comment]
Well, I've used the **argparse** tool that you showed in your book, help (**-h**) option can be used.

Added usage documentation and changed the trackbar order as you asked.

**Comment by jrosebr1** [comment]
@marjinal1st Thanks for the updates. Looks great. Sorry it took me so long to merge in, this has been a terribly busy week for me.

**Comment by marjinal1st** [comment]
No problem :+1:

**Pull request merged**
