### PR TITLE
added support for nvidia jetson camera

### PR DESCRIPTION
**Pull request by al3xsh**
Hi,

I've added support to the videostream class for the in built nvidia jetson tx2 camera using gstreamer functionality.

I've provided a switch in the videostream class to enable this support in the same way as you do for the raspberry pi camera, but am happy to enable the support any other way.

Regards,

Alex

### CODE REVIEW

**Comment by jrosebr1** [comment]
This is a really cool contribution, thanks @al3xsh. I would definitely like to include it in `imutils`; however, since the NVIDIA Jetson is _so_ niche specific I'd like to keep it from the `VideoStream` class factory and instead use _just_ `JetsonVideoStream`. If you can update the PR I'll merge it in.

**Comment by al3xsh** [comment]
@jrosebr1 thanks for the feedback!  I have no problem adding it to it's own class - i'll try to make those changes this week and will update the PR once it's done.

Cheers,

Alex

**Comment by jrosebr1** [comment]
Thanks @al3xsh!

**Comment by abhiTronix** [comment]
Hey @jrosebr1, This PR looks good to be merged, the flag `useJetsonCamera ` flag can definitely be used in `VideoStream` and it will not alter the existing functionality of this class but rather adds to it, will be a nice addition to `imutils `library in my opinion. 👍

**Comment by jrosebr1** [comment]
I agree that it will be a nice addition, I just don't want it called from the `VideoStream` factory, that's all 😄 If it's a standalone class I'm 100% on board with it.

**Comment by al3xsh** [comment]
I have no problem splitting it out as a standalone class. I'm afraid the day job has got in the way recently though!

It's on my to-do list for Christmas! 🤣

Alex

**Comment by al3xsh** [comment]
Right, I *think* I've managed to successfully update the pull request to keep the JetsonVideoStream class in a separate class.

I've tested it on a couple of examples and it seems to work!

Have a good Christmas!

Cheers,

Alex

**Comment by jessetmoody** [comment]
Thanks so much for this al3xsh! Although there were some problems, this really helped me along. Initially, jetsonvideostream.py throws multiple errors and doesn't work for me because it uses the nvcamerasrc plugin, which is deprecated in my version L4T. To make it work, I changed it to use nvarguscamerasrc instead and made some other modifications to the pipeline based on this forum thread (https://devtalk.nvidia.com/default/topic/1042892/jetson-agx-xavier/nvarguscamerasrc-opencv-solved-/).
Here's the modified pipeline code:
```		cameraString = ('nvarguscamerasrc ! '
               			'video/x-raw(memory:NVMM), '
               			'width=(int)1920, height=(int)1080, '
               			'format=(string)NV12, framerate=(fraction)30/1 ! '
               			'nvvidconv ! '
               			'video/x-raw, width=(int){}, height=(int){}, '
               			'format=(string)BGRx ! '
               			'videoconvert ! appsink').format(width, height)
```
I'd like to push this to your pull request, but I don't know if that's possible so I'll just leave this here in case you want to add it. Thanks!

**Pull request closed without merging**
