### PR TITLE
Reduce code complexity for range detector script

### PR DESCRIPTION
**Pull request by marjinal1st**
Just got bored and reduced code complexity in the range detector script. Still works same way.

### CODE REVIEW

**Comment by jrosebr1** [comment]
Merged!

In the future, I think a really cool feature would be for the actual HSV/RGB threshold values be printed to the terminal after a given keypress.

**Comment by marjinal1st** [comment]
Do you mean the values in the trackbars?

**Comment by jrosebr1** [comment]
Yes, that is correct.

**Comment by marjinal1st** [comment]
Well, I was looking for a final PR to get an Hacktoberfest tshirt and you just gave it to me :smile: I'll prepare it :wink:

**Pull request merged**
