### PR TITLE
Added .tif support to list_images

### PR DESCRIPTION
**Pull request by MiliasV**

### CODE REVIEW

**Comment by jrosebr1** [comment]
Nice PR @MiliasV. If we are going to support TIFF let's include both `.tif` and `.tiff` file extensions. Please update the PR and I'll merge it in 😄

**Comment by MiliasV** [comment]
Done :)

**Comment by jrosebr1** [comment]
Merged, thanks @MiliasV!

**Comment by MiliasV** [comment]
No problem @jrosebr1 😃

**Pull request merged**
